/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Thinkpad
 */
public class java5ass extends javax.swing.JFrame {

    /**
     * Creates new form java5ass
     */
    public java5ass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        NAMA = new javax.swing.JLabel();
        ISINAMA = new javax.swing.JTextField();
        ALAMAT = new javax.swing.JLabel();
        ISIALAMAT = new javax.swing.JTextField();
        MAKANAN = new javax.swing.JLabel();
        Ayam = new javax.swing.JCheckBox();
        IKAN = new javax.swing.JCheckBox();
        BEEF = new javax.swing.JCheckBox();
        BABI = new javax.swing.JCheckBox();
        MINUMAN = new javax.swing.JLabel();
        SODA = new javax.swing.JCheckBox();
        MINERAL = new javax.swing.JCheckBox();
        TEA = new javax.swing.JCheckBox();
        COFFE = new javax.swing.JCheckBox();
        ORDER = new javax.swing.JButton();
        TEXTAREA = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NAMA.setText("NAMA");

        ISINAMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISINAMAActionPerformed(evt);
            }
        });

        ALAMAT.setText("ALAMAT");

        ISIALAMAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISIALAMATActionPerformed(evt);
            }
        });

        MAKANAN.setText("MAKANAN");

        Ayam.setText("CHICKEN");
        Ayam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AyamActionPerformed(evt);
            }
        });

        IKAN.setText("FISH");
        IKAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IKANActionPerformed(evt);
            }
        });

        BEEF.setText("BEEF");

        BABI.setText("PORK");

        MINUMAN.setText("MINUMAN");

        SODA.setText("SODA");
        SODA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SODAActionPerformed(evt);
            }
        });

        MINERAL.setText("MINERAL");

        TEA.setText("TEA");

        COFFE.setText("COFFE");

        ORDER.setText("ORDER");
        ORDER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ORDERActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NAMA)
                                    .addComponent(ALAMAT))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ISINAMA)
                                    .addComponent(ISIALAMAT, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(MAKANAN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Ayam)
                                    .addComponent(BEEF))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BABI)
                                    .addComponent(IKAN)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(MINUMAN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SODA)
                                    .addComponent(TEA))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(COFFE)
                                    .addComponent(MINERAL)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(ORDER))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(TEXTAREA, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(264, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NAMA)
                    .addComponent(ISINAMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ALAMAT)
                    .addComponent(ISIALAMAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MAKANAN)
                    .addComponent(Ayam)
                    .addComponent(IKAN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BEEF)
                    .addComponent(BABI))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MINUMAN)
                    .addComponent(SODA)
                    .addComponent(MINERAL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TEA)
                    .addComponent(COFFE))
                .addGap(18, 18, 18)
                .addComponent(ORDER)
                .addGap(18, 18, 18)
                .addComponent(TEXTAREA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ISINAMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISINAMAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ISINAMAActionPerformed

    private void ISIALAMATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISIALAMATActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ISIALAMATActionPerformed

    private void AyamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AyamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AyamActionPerformed

    private void IKANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IKANActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IKANActionPerformed

    private void SODAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SODAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SODAActionPerformed

    private void ORDERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ORDERActionPerformed
           // Mendapatkan data dari TextField
    String nama = NAMA.getText();
    String alamat = ALAMAT.getText();
    
    // Menyimpan daftar makanan yang dipilih
    StringBuilder makanan = new StringBuilder();
    if (Ayam.isSelected()) {
        makanan.append("    - Ayam\n");
    }
    if (IKAN.isSelected()) {
        makanan.append("    - IKAN\n");
    }
    if (BEEF.isSelected()) {
        makanan.append("    - BEEF\n");
    }
    if (BABI.isSelected()) {
        makanan.append("    - BABI\n");
    }

    // Menyimpan daftar minuman yang dipilih
    StringBuilder minuman = new StringBuilder();
    if (SODA.isSelected()) {
        minuman.append("    - SODA\n");
    }
    if (MINERAL.isSelected()) {
        minuman.append("    - MINERAL\n");
    }
    if (TEA.isSelected()) {
        minuman.append("    -TEA \n");
    }
    if (COFFE.isSelected()) {
        minuman.append("    -COFFE \n");
    }
    
    // Menampilkan data di TextArea dengan format yang rapi
    TEXTAREA.setText("NAMA  : " + nama + "\n" +
                        "ALAMAT  : " + alamat + "\n\n" +
                        "MAKANAN : \n" + makanan.toString() + "\n" +
                        "MINUMAN: \n" + minuman.toString());
    }//GEN-LAST:event_ORDERActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(java5ass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(java5ass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(java5ass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(java5ass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
            try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(soal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(soal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(soal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(soal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new java5ass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ALAMAT;
    private javax.swing.JCheckBox Ayam;
    private javax.swing.JCheckBox BABI;
    private javax.swing.JCheckBox BEEF;
    private javax.swing.JCheckBox COFFE;
    private javax.swing.JCheckBox IKAN;
    private javax.swing.JTextField ISIALAMAT;
    private javax.swing.JTextField ISINAMA;
    private javax.swing.JLabel MAKANAN;
    private javax.swing.JCheckBox MINERAL;
    private javax.swing.JLabel MINUMAN;
    private javax.swing.JLabel NAMA;
    private javax.swing.JButton ORDER;
    private javax.swing.JCheckBox SODA;
    private javax.swing.JCheckBox TEA;
    private javax.swing.JTextField TEXTAREA;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables
}
